### ISSUE TITLE
Waiting for base = 0 0

### ISSUE THREAD

**Issue by BobbyDuggart** [Dustio/Gunkolle#22]
heyy, it's that guy who has a million problems with the client cause he's using a 4k tv instead of a normal monitor.
but not really actually, new client works wonderfully, only one issue this time.

When receiving the last doll in a 0-2 run, I get the message "Waiting for base = 0 0" Normally, it would click the doll and return to base, however, now it seems to be clicking the share button. I tried to find where this happens but can't figure it out. I'd assume it's a ClickS, but maybe not? I don't see any ClickS occurring within the 40,70 to 140,120 pixel range.

**Comment by Dustio** [comment]
Lol no problem. During the GoHome function I added a FindClick for the pic ReturnToBase, which appears around the same time and position as the share button. I wasn't having any problems with it, but maybe with an added sleep timer it could work? It could also just be seeing the share button and thinking that is the ReturnToBase pic, so retaking the pic might could fix it too. If that doesn't help you can always just erase the line since the click is only there to save a few seconds.

**Comment by BobbyDuggart** [comment]
I retook the image and added some sleep timers which fixed it. Thanks for the help!
