### ISSUE TITLE
Not a bug report or something

### ISSUE THREAD

**Issue by EchoControl** [Dustio/Gunkolle#24]
Hello,

Just came to say I'm happy that this lives and someone still keeps it up to date! _Also someone dealt with the shitcode I've done_.
Damn, this is really cool! 

Is there anything whats needs to be done, as I would love to continue working on it!

**Comment by Dustio** [comment]
Hey welcome back!

I just finished moving over to the new client and all the basic stuff is working again. The only thing I have an issue with atm is the new client itself.. I was getting a lot of crashes and slowdown during expedition only, but fixed some of it by switching to 8gb ram on the emulator. Now it just crashes less often lol. Idk how many more people have these issues but I've been looking for different emulator versions and graphics drivers that might make it better. I also tried using LDPlayer Android 7.1, which I know nothing about,  and for some reason some clicks weren't registering, so I guess the script only works on Android 5.1 for now.

Anyway, the only things that I can think of that could be worked on are some of the features that were in old builds of Gunkolle, like an option for factory production check and timed combat simulation. I haven't even started to look into how those were implemented so all we have is what was there before. Other than that maybe you can find something to clean up that I made a mess of lol.

I also know some people who have slower computers/internet connection need to increase the sleep timers on some maps due to how they're using ClickS for the most part,  but I'm not sure how to account for that.

That's about where I'm at with everything. I wasn't working on a whole lot right now but maybe you can throw some stuff at it.

**Comment by EchoControl** [comment]
Why LDPlayer though?

**Comment by Dustio** [comment]
I switched to LDPlayer back when it was the only emulator to support 60 fps on GFL. When the client got high fps mode I tried a bunch of emulators and none of them preformed better than LD for me, so i just stuck with it. 

It's possible there could be a better one now - I just haven't looked in a while or needed to switch away from LD. BobbyDuggart's repository uses Nox still.

**Comment by BobbyDuggart** [comment]
"The only thing I have an issue with atm is the new client itself.. I was getting a lot of crashes and slowdown during expedition only, but fixed some of it by switching to 8gb ram on the emulator."

I've been running expedition only overnight for the past 3 nights and it seems to be working well. I'm running two clients at 20fps, 2 core cpu, 4gb ram. I don't play gfl on the pc I run the bot on, so I run at the lowest possible settings. my mobile game pc costs like 300 dollars and is probably the reason i need to add 1000 to every sleep timer, but it's pretty reliable. On the old client I think my record is 200 something 0-2 runs without error. I haven't tried stress testing the new client, but it got to 120 0-2 runs the other day without me messing with it. I assume, since memory leaks are now gone, this thing will probably do 300+ runs without stopping. you could probably get banned before the client decided to stop working lol. Anyways, if you wanna try my edit, I'm running Nox 6.6.0.0. and my emulator is named 1STCLIENT. I think my version actually works on LDPlayer too, you just have to set the window ID to 1STCLIENT.

"I also know some people who have slower computers/internet connection need to increase the sleep timers on some maps due to how they're using ClickS for the most part, but I'm not sure how to account for that."

i stg, there's a MinWait and MaxWait feature on this fucking client that, the minute you touch them, instantly break the client. They're set to 3000 by default but even if you change the values back to 3000, the client no longer works once you've touched it. idk what MinWait/MaxWait was meant to do originally, but if you could figure out a sleep timer multiplier that would be amazing. Every time a new version is released I have to change all the sleep timers manually. If I could, say, increase all sleep timers by 1000 with a button in the UI that would be very nice.
Either way, looking at the code/image changes in the new client, it looks like you did a shitton of work to get this thing updated so thank you for that.

**Comment by Dustio** [comment]
I'll try to disable high frame rate mode when using expedition only and see if it stops crashing. I used to have it on all the time with the old client with no issues, but maybe they'll eventually optimize it. I'm pretty sure it's not the emulator either because I got the same crashes on my phone too. 

I've never actually used the Min/MaxWait before lol. After looking through AHKanColle, it stated that is was used for "time to wait after exped returns". It was also used for combatsim timers, but I don't know how any of that works atm.

**Comment by DatarisRemiel** [comment]
My biggest issue with the new client is that it tends to hard freeze rather than full crash when a Training timer completes, so the existing crash recovery code doesn't really function. It shouldn't be too hard to write a method on the idle screen to see if the banner is still changing every 5 seconds or whatever and manually swipe the client closed in the emulator.

**Comment by Dustio** [comment]
Yeah I've thought about how to fix that but couldn't think of a way that works with the existing expedition check, since it's currently looking for pictures to appear at any time, but maybe with timers it's possible.

**Comment by BobbyDuggart** [comment]
Any of you using Live2D/animated tdolls on your home screen? Just got my first main menu freeze and it was after I switched to an animated doll. idk just a thought.

**Comment by DatarisRemiel** [comment]
I've had freezes with all three types: static, basic animation and Live2D. It's almost always been when a doll returns from Skill Training.

**Comment by BobbyDuggart** [comment]
oooh, thanks for the info. I'll test it out when i have more than like 20 data.

**Comment by BobbyDuggart** [comment]
wow! another client update.
you think this one will annihilate the bot?

Also, I'm not even using Gunkolle right now. this is a good thing because it means I don't have to worry about the program not working. it's also a bad thing because it means I have zero motivation to help fix the bot since I don't need it (not that i provided much help in the first place lol).

anyways no rush (at least on my end). I'm approaching top 100 so there's no point in leveling anymore. not sure how the rest of you guys are doing, but that's where I'm at right now.
