### ISSUE TITLE
GFL updates to the new client a lot more frequently now, which means you have to reinstall the apk (and all other files) to run the script. Any plans to eventually adapt the code for the new client? 

### ISSUE THREAD

**Issue by SwordfishWithGlasses** [Dustio/Gunkolle#9]
There is a chance that old client simply stops working in the future (although I doubt anytime soon). The new client has issues, but is generally a step up from the old one. I know this would be a rather intensive process, but do you intend to eventually update the script to the new client? 

Also, it would be cool to add some guides in the readme on how to make custom map routes and add dolls, the latter of which is actually very easy.

**Comment by BobbyDuggart** [comment]
"Also, it would be cool to add some guides in the readme on how to make custom map routes"
+1 to this. I was actually gonna ask this once I get some more free time, just too busy right now to figure out how some of the functions work.

An update to the new client would be nice as well, as I was thinking about using this for an old CN account I have, since CN is currently using the new client.

**Comment by Dustio** [comment]
I was planning on moving to the new client if they threw out the old one. Tbh I haven't used the new client much at all but from what I've seen it there are already some alarming obstacles to work around, one being how repairing works. Because the repair tab pops up whenever a doll is damaged and not critically damaged, it will be difficult for the script to recognize when to repair. I have some ideas on how I could make it work but I haven't tried them and I have doubts about consistency, so I've just been putting it off for later lol. 

Making custom maps can be about as simple as adding dolls, it just takes more time to find coords and such. I could make a quick guide on it later.

**Comment by yocool13** [comment]
You can disable the client from automatically updating in the Google Play Store, just click the three dots button and untick "Auto Update".
![Screenshot_20200304-130257](https://user-images.githubusercontent.com/10333247/75877716-96c5e880-5e18-11ea-8da3-903518fb220c.png)
